### ISSUE TITLE
Mobs that dont have mob eggs

### ISSUE THREAD

**Issue by 15987632** [DrkMatr1984/EggCatcher#1]
Mobs such as iron golems, withers, enderdragons when u capture them they drop an egg with the right mod data but because it isnt in vanilla minecraft the egg doesnt work.

**Comment by DrkMatr1984** [comment]
Hmm, EnderDragons seem to work for me, although not in conjunction with SilkSpawners. Can you test the newest version here : 
https://www.dropbox.com/s/46tso26xc7lq6dq/EggCatcher-1.8-Beta.jar?dl=0
And try to spawn EnderDragons with the Egg provided upon Capture? Also, I've added ElderGuardian Variants and the Ability to capture mobs by smacking them with an egg as well as throwing the egg. 
Try this stuff out and report any bugs you find please!
